FileVersion = 1
Dependencies = {corlib = "*", SDL3Native = "*", "Sedulous.RHI.HLSLShaderCompiler" = "*", "Sedulous.RHI.Vulkan" = "*", "Sedulous.Platform.SDL3" = "*"}

[Project]
Name = "Sedulous.RHI.Renderer"
StartupObject = "Sedulous.RHI.Renderer.Program"
