FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Mathematics" = "*", "Sedulous.IO" = "*", SDL3_image = "*"}

[Project]
Name = "Sedulous.Imaging"
TargetType = "BeefLib"
StartupObject = "Sedulous.Imaging.Program"
