FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Foundation" = "*", "Sedulous.Engine.Core" = "*"}

[Project]
Name = "Sedulous.Engine.Renderer"
TargetType = "BeefLib"
StartupObject = "Sedulous.Engine.Renderer.Program"
