FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Engine.Audio.OpenAL" = "*", "Sedulous.Engine.Input" = "*", "Sedulous.Engine.Navigation" = "*", "Sedulous.Engine.Physics" = "*", "Sedulous.Platform.SDL3" = "*", "Sedulous.RHI.Vulkan" = "*", "Sedulous.Runtime" = "*", "Sedulous.Engine.Renderer.RHI" = "*"}

[Project]
Name = "SampleGame"
StartupObject = "SampleGame.Program"
