FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Mathematics" = "*", "Sedulous.Imaging" = "*"}

[Project]
Name = "Sedulous.Model"
TargetType = "BeefLib"
StartupObject = "Sedulous.Model.Program"
