FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Engine.Audio.OpenAL" = "*", "Sedulous.Geometry" = "*", "Sedulous.Platform.SDL3" = "*", "Sedulous.Engine.Navigation" = "*", "Sedulous.Imaging" = "*", "Sedulous.RHI.Vulkan" = "*", "Sedulous.Runtime" = "*", "Sedulous.Engine.Input" = "*", "Sedulous.Engine.Physics" = "*", "Sedulous.Engine.Renderer.RHI" = "*"}

[Project]
Name = "RHISandbox"
StartupObject = "RHISandbox.Program"
