FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Engine.Core" = "*", "Sedulous.Platform.Core" = "*"}

[Project]
Name = "Sedulous.Runtime"
TargetType = "BeefLib"
StartupObject = "Sedulous.Runtime.Program"
