FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Foundation" = "*", "Sedulous.Mathematics" = "*"}

[Project]
Name = "Sedulous.Geometry"
TargetType = "BeefLib"
StartupObject = "Sedulous.Geometry.Program"
