FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Engine.Audio.OpenAL" = "*", "Sedulous.Engine.Navigation" = "*", "Sedulous.Engine.Physics" = "*", "Sedulous.Platform.SDL3" = "*", "Sedulous.Engine.Renderer.SDL" = "*", "Sedulous.Runtime" = "*", "Sedulous.Engine.Input" = "*"}

[Project]
Name = "Sandbox"
StartupObject = "Sandbox.Program"

[Configs.Debug.Win64]
BeefLibType = "Static"
