FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Foundation" = "*", "Sedulous.Messaging" = "*"}

[Project]
Name = "Sedulous.SceneGraph"
TargetType = "BeefLib"
StartupObject = "Sedulous.SceneGraph.Program"
