FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Foundation" = "*", "Sedulous.Jobs" = "*", "Sedulous.Messaging" = "*", "Sedulous.Resources" = "*", "Sedulous.SceneGraph" = "*"}

[Project]
Name = "Sedulous.Engine.Core"
TargetType = "BeefLib"
StartupObject = "Sedulous.Engine.Core.Program"
