FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Engine.Core" = "*", "Sedulous.Geometry" = "*"}

[Project]
Name = "Sedulous.Engine.Navigation"
TargetType = "BeefLib"
StartupObject = "Sedulous.Engine.Navigation.Program"
