FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Foundation" = "*", "Sedulous.Mathematics" = "*"}

[Project]
Name = "Sedulous.Platform.Core"
TargetType = "BeefLib"
StartupObject = "Sedulous.Platform.Core.Program"
