FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Mathematics" = "*"}

[Project]
Name = "Sedulous.Mathematics.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.Mathematics.Tests.Program"
